# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Object-Iterate
version:      1.09
version_from: lib/Iterate.pm
installdirs:  site
requires:
    Test::Data:                    0
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
