--- #YAML:1.0
name:                Object-Iterate
version:             1.11
abstract:            iterators for objects that know the next element
license:             perl
generated_by:        ExtUtils::MakeMaker version 6.36
distribution_type:   module
requires:     
    Test::Data:                    0
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
author:
    - brian d foy <bdfoy@cpan.org>
